src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => 'Électrique',
        1 => 'Gaz'
    ];

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->sold = false;
        $this->features = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *     min="10",
     *     max="400"
     * )
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Feature", inversedBy="properties")
     */
    private $features;

    /**
     * @ORM\Column(type="string")
     * @var string|null
     */
    private $fileName;

    /**
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="fileName")
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug() :string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice()
    {
        return number_format($this->price, 0, ',', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType()
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Feature[]
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Feature $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features[] = $feature;
            $feature->addProperty($this);
        }

        return $this;
    }

    public function removeFeature(Feature $feature): self
    {
        if ($this->features->contains($feature)) {
            $this->features->removeElement($feature);
            $feature->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string|null $fileName
     * @return Property
     */
    public function setFileName(?string $fileName): Property
    {
        $this->fileName = $fileName;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;

        // Only change the updated af if the file is really uploaded to avoid database updates.
        // This is needed when the file should be set when loading the entity.
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Feature;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('features', EntityType::class, [
                'class'        => Feature::class,
                'choice_label' => 'name',
                'multiple'     => true,
                'required'     => false
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    public function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $key => $choice) {
            $output[$choice] = $key;
        }

        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @Route("/biens", name="property_index")
     * @param PropertyRepository $propertyRepository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PropertyRepository $propertyRepository, PaginatorInterface $paginator, Request $request)
    {
        $search = new PropertySearch();

        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $property = $paginator->paginate(
            $propertyRepository->findAllVisible($search),
            $request->query->getInt('page', 1),
            12
            );

        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $property,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property_show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @param PropertyRepository $propertyRepository
     * @return Response
     */
    public function show(Property $property, string $slug, PropertyRepository $propertyRepository)
    {
        if ($property->getSlug() !== $slug) {
            $this->redirectToRoute('property_show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        return $this->render('property/show.html.twig', [
            'current_menu' => 'properties',
            'property' => $property
        ]);
    }
}

templates/property/_property.html.twig
{# @var property \App\Entity\Property  #}
<div class="card mb-4">
    {% if property.fileName %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="" class="card-img-top" style="width: 100%; height: auto">
    {% else %}
        <img src="{{ asset('images/properties/delivreuses.jpg') | imagine_filter('thumb') }}" alt="" class="card-img-top" style="width: 100%; height: auto">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property_show', {'slug': property.slug, 'id': property.id}) }}">
                {{ property.title }}
            </a>
        </h5>

        <p class="card-text">
            {{ property.surface }} m<sup>2</sup> - {{ property.city }} ({{ property.postalCode }})
        </p>

        <div class="text-primary" style="font-size: 2rem; font-weight:bold;">
            {{ property.formatedPrice }}
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos biens{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.features) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-info">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>

        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>

        <div class="navigation">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title }}{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    {% if property.fileName %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="" class="card-img-top" style="width: 100%; height: auto">
                    {% else %}
                        <img src="{{ asset('images/properties/delivreuses.jpg') | imagine_filter('medium') }}" alt="" class="card-img-top" style="width: 100%; height: auto">
                    {% endif %}
                </div>

                <div class="col-md-4">

                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m2</h2>

                    <div class="text-primary" style="font-size: 4rem; font-weight: bold">{{ property.formatedPrice }}€
                    </div>

                    <a href="#" class="btn btn-primary">Contacter l'agence</a>

                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">

                <p>
                    {{ property.description | nl2br }}
                </p>

                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m2</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Étages</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>

            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul>
                    {% for feature in property.features %}
                        <li class="list-group-item">{{ feature.name }}</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
    </div>
{% endblock %}